name: Deploy Blog Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 设置 Node.js 版本为 22.11.0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      # 安装 pnpm 版本 9.14.4
      - name: Install pnpm
        run: npm install -g pnpm@9.14.4

      # 使用 pnpm 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 使用 pnpm 运行构建命令
      - name: Build
        run: pnpm run docs:build

      # 部署到 Nginx 服务器
      - name: Deploy to Nginx Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          #scp -r ./docs/.vuepress/dist/* $SSH_USERNAME@$SSH_HOST:$REMOTE_PATH
          sshpass -p $SSH_PASSWORD scp -r ./dev-ops/Plume/nginx/html/* root@$SSH_HOST:$REMOTE_PATH
